# Generated by Django 3.2 on 2022-12-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20221206_2258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credit',
            table='loans',
        ),
    ]
