# Generated by Django 3.2 on 2022-12-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_credit_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.account'),
        ),
    ]
